stages:
  - e2e-tests
variables:
  KUBECTL: v1.19.3
  KIND: v0.9.0
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
.kind_deployment:
  stage: e2e-tests
  image: docker:stable
  services:
    - name: $CI_REGISTRY_GO/docker:18.09.7-dind
      alias: docker
  tags:
    - go
  script:
    - apk add -U wget git go curl
    - wget -q -o /dev/null -O &> /dev/null /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -q -o /dev/null -O &> /dev/null /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - sed -i "s/K8S_VERSION/$K8S_VERSION/g" ".gitlab/kind-config.yaml"
    - kind create cluster --name=dev --config=./.gitlab/kind-config.yaml
    - sed -i -E -e "s/localhost|0\.0\.0\.0|127\.0\.0\.1/docker/g" "$HOME/.kube/config"
    - sed -i -E -e "s/localhost|0\.0\.0\.0|127\.0\.0\.1/docker/g" "deploy/tests/ci.sh"
    - sed -i -E -e "s/localhost|0\.0\.0\.0|127\.0\.0\.1/docker/g" "deploy/tests/e2e/client.go"
    - until kubectl get nodes -o wide;do sleep 2; done
    - CI_ENV=gitlab deploy/tests/create.sh
    - KIND_URL=docker go test -v ./deploy/tests/e2e/... --tags=e2e_parallel
    - KIND_URL=docker go test -v -p 1 ./deploy/tests/e2e/... --tags=e2e_sequential
  after_script:
    - kind delete cluster --name=dev
k8s_19:
  variables:
    K8S_VERSION: v1.19.3
  extends: .kind_deployment
